<script lang="ts">
	import type { EmailData } from '@/types/index';
	import { toast } from '@zerodevx/svelte-toast';
	import { onMount } from 'svelte';

	export let color: string = '#4b5563';
	export let hoverColor: string = '#2563eb';
	export let data: EmailData;
	let mailToURL: string;
	let currentColor = color;

	export let classes: string = 'absolute top-4 right-4';
	let emailBtn: HTMLAnchorElement;
	let svgElement: SVGSVGElement;
	onMount(() => {
		emailBtn.addEventListener('click', sendEmail);

		const checkoutLink = data.link ? `Checkout this link! ${window.location.href}\n\n` : '';
		const mailToBody = `${data.body}.\n\n This email was generated by castaway-voters webapp.`;
		const to: string = data.to ?? '';
		const subject: string = data.subject ?? '';
		const encodedSubject = encodeURIComponent(subject);
		const encodedCheckoutLink = encodeURIComponent(checkoutLink);
		const encodedBody = encodeURIComponent(mailToBody);

		mailToURL = `mailto:${to}?subject=${encodedSubject}&body=${encodedCheckoutLink}${encodedBody}`;

		svgElement.addEventListener('mouseover', () => {
			currentColor = hoverColor;
		});
		svgElement.addEventListener('mouseout', () => {
			currentColor = color;
		});
		function sendEmail() {
			toast.push('Open email to continue', {
				theme: { '--toastBackground': 'green', '--toastBarBackground': 'limegreen' },
				duration: 6900
			});
			setTimeout(() => {
				toast.pop(0);
			}, 20000);
		}
	});
</script>

<a href={mailToURL} role="button" bind:this={emailBtn}
	><svg
		class={classes}
		bind:this={svgElement}
		width="26"
		height="26"
		viewBox="0 0 61 61"
		fill="none"
		xmlns="http://www.w3.org/2000/svg"
	>
		<path
			d="M55.681 30.7112V11.9612H30.681H5.681V30.7112V49.4612H30.681"
			stroke={currentColor}
			stroke-width="5"
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			d="M55.681 43.2112H38.181"
			stroke={currentColor}
			stroke-width="5"
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			d="M49.431 36.9612L55.681 43.2112L49.431 49.4612"
			stroke={currentColor}
			stroke-width="5"
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
		<path
			d="M5.681 11.9612L30.681 30.7112L55.681 11.9612"
			stroke={currentColor}
			stroke-width="5"
			stroke-linecap="round"
			stroke-linejoin="round"
		/>
	</svg>
</a>
